version: '3.1'

services:
  php:
    image: php:7.4-apache
    ports:
      - 8050:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8051:8080
